name: Cypress E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Cypress repo
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Install Cypress dependencies
        run: npm install


      - name: Clone API repo
        run: git clone https://github.com/CoryKelly/qa-testing-playground-api ../api


      - name: Install API dependencies
        working-directory: ../api
        run: npm install


      - name: Start API
        working-directory: ../api
        run: |
          nohup npm run dev > api.log 2>&1 &
          sleep 5


      - name: Wait for API
        run: npx wait-on http://localhost:3000 --timeout 60000


      - name: Clone UI repo
        run: git clone https://github.com/CoryKelly/qa-testing-playground-ui ../ui


      - name: Install UI dependencies
        working-directory: ../ui
        run: npm install


      - name: Start UI
        working-directory: ../ui
        run: |
          nohup npm run dev -- --host > ui.log 2>&1 &
          sleep 5


      - name: Wait for UI
        run: npx wait-on http://localhost:5173 --timeout 60000


      - name: Run Cypress tests
        run: npx cypress run --browser chrome